openapi: 3.0.0
info:
  title: Cohere-based RAG Chatbot API
  description: API for RAG chatbot that answers questions from book content
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Check if the service is running and all dependencies are accessible
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                  dependencies:
                    type: object
                    properties:
                      cohere:
                        type: boolean
                      qdrant:
                        type: boolean
                      postgres:
                        type: boolean

  /rag/book-wide:
    post:
      summary: Book-wide Q&A
      description: Ask questions about the entire book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - session_id
              properties:
                query:
                  type: string
                  description: The question to ask about the book
                  example: "What are the main concepts in chapter 3?"
                session_id:
                  type: string
                  description: Unique identifier for the user session
                  example: "sess_12345"
                metadata:
                  type: object
                  description: Additional metadata for the query
                  example: {"chapter_filter": "3"}
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                type: object
                required:
                  - answer
                  - sources
                  - session_id
                properties:
                  answer:
                    type: string
                    description: The generated answer
                    example: "The main concepts in chapter 3 include..."
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                          description: ID of the source chunk
                        text_preview:
                          type: string
                          description: Preview of the source text
                        relevance_score:
                          type: number
                          description: Relevance score of this source
                        location:
                          type: object
                          description: Location information in the book
                  session_id:
                    type: string
                    description: The session identifier
                  confidence:
                    type: number
                    description: Confidence score of the response (0-1)
        '400':
          description: Bad request - invalid input
        '404':
          description: No relevant content found for the query
        '500':
          description: Internal server error

  /rag/selected-text:
    post:
      summary: Selected-text Q&A
      description: Ask questions about user-provided text only (ignores global context)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - selected_text
                - session_id
              properties:
                query:
                  type: string
                  description: The question about the selected text
                  example: "Explain this concept?"
                selected_text:
                  type: string
                  description: The text the user has selected/highlighted
                  example: "Embodied AI involves the interaction between..."
                session_id:
                  type: string
                  description: Unique identifier for the user session
                  example: "sess_12345"
                metadata:
                  type: object
                  description: Additional metadata for the query
                  example: {}
      responses:
        '200':
          description: Successful response with answer based only on selected text
          content:
            application/json:
              schema:
                type: object
                required:
                  - answer
                  - sources
                  - session_id
                properties:
                  answer:
                    type: string
                    description: The generated answer based only on selected text
                    example: "This concept refers to..."
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        source_type:
                          type: string
                          description: "Value: 'selected_text'"
                        text_preview:
                          type: string
                          description: Preview of the selected text used
                        confidence:
                          type: number
                          description: Confidence score of the response (0-1)
                  session_id:
                    type: string
                    description: The session identifier
                  mode:
                    type: string
                    description: "Value: 'selected_text'"
        '400':
          description: Bad request - invalid input
        '500':
          description: Internal server error

components:
  schemas:
    SourceReference:
      type: object
      properties:
        chunk_id:
          type: string
          description: ID of the source chunk
        text_preview:
          type: string
          description: Preview of the source text
        relevance_score:
          type: number
          description: Relevance score of this source (0-1)
        location:
          type: object
          description: Location information in the book
          properties:
            book_id:
              type: string
            chapter:
              type: string
            page:
              type: number
            section:
              type: string